### PR TITLE
vendorizing dependencies

### PR DESCRIPTION
**Pull request by andrewsmedina**
Vendorizing all deps with [govendor](https://github.com/kardianos/govendor):

```
govendor init
govendor add +external
```

### CODE REVIEW

**Comment by flavioribeiro** [comment]
@andrewsmedina thanks for that, we must find a way to avoid counting the vendor files on the project coverage

**Comment by flavioribeiro** [comment]
also, should we update the dependencies on every build or tag? what's the correct way to update vendorized dependencies?

**Comment by albertoleal** [comment]
@flavioribeiro it should be fine to use `--skipPackage` to skip dependencies.

**Comment by andrewsmedina** [comment]
@flavioribeiro we should update dependencies when we need to do it.

**Comment by flavioribeiro** [comment]
hey @andrewsmedina thanks for this one. I'm talking with @fsouza and we think it's better to wait until the [1.0](https://github.com/snickers/snickers/releases) so we can vendorize the deps. Right now we are still debating if it makes sense to have `gonfig`, `lager` and others!

Anyway, thank you and I hope to see more contributions from you. 🍻

**Comment by andrewsmedina** [comment]
I can't see problems in to vendorize deps before 1.0 since govendor has commands to add, update and remove deps from vendor.

**Pull request closed without merging**
